class Some_PLayers(object):
    '''
    Not defined in documentation
    ============
    Some players
    ============
    * AUDACIOUS = "audacious"
    * BANSHEE = "banshee"
    * BEATBOX = "beatbox"
    * BMP = "bmp"
    * CLEMENTINE = "clementine"
    * DRAGONPLAYER = "dragonplayer"
    * EXAILE = "exaile"
    * GMUSICBROWSER = "gmusicbrowser"
    * GMPC = "gmpc"
    * GUAYADEQUE = "guayadeque"
    * MOPIDY = "mopidy"
    * MPDRIS = "mpDris"
    * QUODLIBET = "quodlibet"
    * RAVEND = "ravend"
    * RHYTHMBOX = "rhythmbox"
    * SPOTIFY = "spotify"
    * VLC = "vlc"
    * XBMC = "xbmc"
    * XMMS2 = "xmms2"
    * XNOISE = "xnoise"
    '''
    #Some players
    AUDACIOUS = "audacious"
    BANSHEE = "banshee"
    BEATBOX = "beatbox"
    BMP = "bmp"
    CLEMENTINE = "clementine"
    DRAGONPLAYER = "dragonplayer"
    EXAILE = "exaile"
    GMUSICBROWSER = "gmusicbrowser"
    GMPC = "gmpc"
    GUAYADEQUE = "guayadeque"
    MOPIDY = "mopidy"
    MPDRIS = "mpDris"
    QUODLIBET = "quodlibet"
    RAVEND = "ravend"
    RHYTHMBOX = "rhythmbox"
    SPOTIFY = "spotify"
    VLC = "vlc"
    XBMC = "xbmc"
    XMMS2 = "xmms2"
    XNOISE = "xnoise"